# From https://github.com/marketplace/actions/wait-for-netlify
name: Lighthouse CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  lighthouse-audit:
    name: Lighthouse Audit
    runs-on: ubuntu-latest
    steps:
      # This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
      - uses: actions/checkout@v2
      # Wait for Netlify deployment from zinzan.netlify.app
      - name: Wait for Netlify deployment
        uses: kamranayub/wait-for-netlify-action@v2.0.3
        id: netlify
        with:
          site_name: "zinzan"
          max_timeout: 10 # Timeout is 10s, adjust depending on average build time
        env: 
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
      # Based on netlify url, run Lighthouse audit
      - name: Run Lighthouse audit
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: https://zinzan.netlify.app
          uploadArtifacts: true # Save results as an action artifacts
          temporaryPublicStorage: true # Upload lighthouse report to the temporary storage
          runs: 3 # Increase accuracy of results by running Lighthouse three times
          serverBaseUrl: ${{ secrets.LHCI_SERVER_URL }} # Use Heroku app to store Lighthouse results
          serverToken: ${{ secrets.LHCI_SERVER_TOKEN }}