# From https://github.com/marketplace/actions/lighthouse-audit
name: Lighthouse CI for Netlify sites
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - name: Audit Netlify deploy preview
      uses: jakejarvis/lighthouse-action@master
      with:
        netlify_site: 'zinzan.netlify.app'
    - uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'
